apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: grupp2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name: wordpress
          image: bitnami/wordpress
          env:
            - name: WORDPRESS_DATABASE_HOST
              value: mariadb
            - name: WORDPRESS_DATABASE_PORT_NUMBER
              value: "3306"
            - name: WORDPRESS_DATABASE_USER
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: username
            - name: WORDPRESS_DATABASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb-secret
                  key: password
            - name: WORDPRESS_DATABASE_NAME
              value: wordpress
            - name: WORDPRESS_USERNAME
              value: admin
            - name: WORDPRESS_PASSWORD
              value: myrootpassword
            - name: WORDPRESS_EMAIL
              value: user@example.com
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          volumeMounts:
            - name: wordpress-storage
              mountPath: /bitnami/wordpress
      volumes:
        - name: wordpress-storage
          persistentVolumeClaim:
            claimName: wordpress-data
